In [ ]:
import pandas as pd
import numpy as nb

In [6]:
#load and read the file
lux = pd.read_csv("C:\\Users\\ABHISHEK\\Documents\\Data Science\\Luxury Housing Banglore_project\\Luxury_Housing_Bangalore.csv")

In [7]:
lux.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.75084604,Primary,NRI,31-03-2025,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.29215187,Primary,Other,30-06-2024,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.51772441,Primary,HNI,31-12-2023,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494,Primary,HNI,31-03-2024,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.34539244,Secondary,HNI,31-12-2024,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [8]:
lux.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [9]:
lux.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [10]:
lux.tail()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004,Secondary,CXO,31-12-2024,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.82937316,Primary,CXO,30-09-2024,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.18330315,Primary,NRI,31-12-2023,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.91415638,Secondary,Other,30-06-2024,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,31-12-2023,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [12]:
lux.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [13]:
#remove the invaild values
lux = lux[lux['Unit_Size_Sqft']> 0]

In [14]:
lux.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90449 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           90449 non-null  object
 1   Micro_Market          90449 non-null  object
 2   Project_Name          90449 non-null  object
 3   Developer_Name        90449 non-null  object
 4   Unit_Size_Sqft        90449 non-null  float64
 5   Configuration         90449 non-null  object
 6   Ticket_Price_Cr       81432 non-null  object
 7   Transaction_Type      90449 non-null  object
 8   Buyer_Type            90449 non-null  object
 9   Purchase_Quarter      90449 non-null  object
 10  Connectivity_Score    90449 non-null  float64
 11  Amenity_Score         81442 non-null  float64
 12  Possession_Status     90449 non-null  object
 13  Sales_Channel         90449 non-null  object
 14  NRI_Buyer             90449 non-null  object
 15  Locality_Infra_Score  90449 non-null  float64
 16  Avg_Traffic_Time_Min  90449 non-null  int64
 17  Buyer_Comments        74057 non-null  object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.1+ MB

In [ ]:
#fix ticket price cr.
#.loc i use because pandas value dont take value that why i use .loc


lux.loc[:,'Ticket_Price_Cr'] = pd.to_numeric( lux['Ticket_Price_Cr'].astype(str).str.replace("Cr","").str.strip(),errors='coerce')

In [48]:
#convert NRI_buyer
lux.loc[:, 'NRI_Buyer'] = lux['NRI_Buyer'].astype(str).str.strip().str.lower()

C:\Users\ABHISHEK\AppData\Local\Temp\ipykernel_13856\744944535.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['0.0' '0.0' '0.0' ... '0.0' '0.0' '0.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  lux.loc[:, 'NRI_Buyer'] = lux['NRI_Buyer'].astype(str).str.strip().str.lower()

In [52]:
lux.loc  [:, 'NRI_Buyer'] = lux['NRI_Buyer'].map({'yes': 1, 'no' : 0})

In [ ]:
#convert datatime
lux.loc[:, 'Purchase_Quarter'] = pd.to_datetime(lux['Purchase_Quarter'])

In [61]:
lux.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90449 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           90449 non-null  object
 1   Micro_Market          90449 non-null  object
 2   Project_Name          90449 non-null  object
 3   Developer_Name        90449 non-null  object
 4   Unit_Size_Sqft        90449 non-null  float64
 5   Configuration         90449 non-null  object
 6   Ticket_Price_Cr       90449 non-null  float64
 7   Transaction_Type      90449 non-null  object
 8   Buyer_Type            90449 non-null  object
 9   Purchase_Quarter      90449 non-null  datetime64[ns]
 10  Connectivity_Score    90449 non-null  float64
 11  Amenity_Score         81442 non-null  float64
 12  Possession_Status     90449 non-null  object
 13  Sales_Channel         90449 non-null  object
 14  NRI_Buyer             90449 non-null  float64
 15  Locality_Infra_Score  90449 non-null  float64
 16  Avg_Traffic_Time_Min  90449 non-null  int64
 17  Buyer_Comments        74057 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(10)
memory usage: 15.1+ MB

In [54]:
lux.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr         25337
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score            9007
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          16392
dtype: int64

In [ ]:
#handle missing values

lux_unit = lux['Unit_Size_Sqft'].mean()

lux_unit

np.float64(6005.6250925936165)

In [38]:
lux.loc[:,'Unit_Size_Sqft'] = lux['Unit_Size_Sqft'].fillna(lux_unit)

In [36]:
lux.describe()

,Unit_Size_Sqft,Ticket_Price_Cr,Purchase_Quarter,Connectivity_Score,Amenity_Score,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90449.000000,65112.000000,90449,90449.000000,81442.000000,0.0,90449.000000,90449.000000
mean,6005.625093,12.725188,2024-05-15 03:40:44.325531392,6.992758,7.505104,NaN,7.496787,67.196630
min,3000.000000,-0.519437,2023-06-30 00:00:00,4.000031,5.000224,NaN,5.000013,15.000000
25%,4504.000000,10.009622,2023-09-30 00:00:00,5.492987,6.263352,NaN,6.245453,41.000000
50%,6004.000000,12.042365,2024-03-31 00:00:00,6.986292,7.501305,NaN,7.493385,67.000000
75%,7505.000000,14.100774,2024-09-30 00:00:00,8.490120,8.752609,NaN,8.749119,93.000000
max,8999.000000,100.000000,2025-03-31 00:00:00,9.999970,9.999865,NaN,9.999956,119.000000
std,1731.456179,7.693135,NaN,1.731630,1.439752,NaN,1.443029,30.236733

In [55]:
lux['NRI_Buyer'].unique()

array([0.])

In [53]:
lux['NRI_Buyer'].fillna(0, inplace=True)

C:\Users\ABHISHEK\AppData\Local\Temp\ipykernel_13856\395315303.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  lux['NRI_Buyer'].fillna(0, inplace=True)
C:\Users\ABHISHEK\AppData\Local\Temp\ipykernel_13856\395315303.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lux['NRI_Buyer'].fillna(0, inplace=True)

In [57]:
lux_ticket = lux['Ticket_Price_Cr'].mean()

lux_ticket

np.float64(12.725187770165439)

In [59]:
lux.loc[:,'Ticket_Price_Cr'] = lux['Ticket_Price_Cr'].fillna(lux_ticket)

In [60]:
lux.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr             0
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score            9007
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          16392
dtype: int64

In [ ]:
lux_amenity = lux['Amenity_Score'].mean()

lux_amenity

In [ ]:
lux.loc[:,'Amenity_Score'] = lux['Amenity_Score'].fillna(lux_amenity)